[INFO]  Starting some_module...
[DEBUG] Command line arguments:

  ['/home/tero/Git/python-cli-submodule/some_module/__main__.py', '-vvv']

[DEBUG] Configuration:

  {'config_file': '/home/tero/.config/some_module/some_module.config',
   'dryrun': False,
   'kissa': 123,
   'koira': 'Musti',
   'log_file': '/home/tero/.local/state/some_module/log/some_module.log',
   'log_level': 'DEBUG',
   'log_max_bytes': 102400,
   'log_max_files': 10,
   'paths': [],
   'verbosity': 'DEBUG'}

[INFO]  Running some code...some_module.some_module
[ERROR] An error occurred:

  [Errno 2] No such file or directory: 'Something that does not exist'

